-- +FlywayNonRepeatable
INSERT INTO estados (estadoId, nombre, paisId)
VALUES (1, 'San José', 1), 
       (2, 'Alajuela', 1), 
       (3, 'Cartago', 1),
       (4, 'Heredia', 1),
       (5, 'Limon', 1),
       (6, 'Puntarenas', 1),
       (7, 'California', 2), 
       (8, 'Texas', 2),
       (9, 'Florida', 2),
       (10, 'Nueva York', 2),
       (11, 'Buenos Aires', 3), 
       (12, 'Córdoba', 3),
       (13, 'Santa Fe', 3),
       (14, 'Mendoza', 3),
       (15, 'São Paulo', 4), 
       (16, 'Río de Janeiro', 4),
       (17, 'Minas Gerais', 4),
       (18, 'Bahía', 4),
       (19, 'Ontario', 5), 
       (20, 'Quebec', 5),
       (21, 'Alberta', 5),
       (22, 'British Columbia', 5);
